Ejercicio 1

Crea un programa que lea una secuencia de caracteres, guarde cada caracter en una posición de una lista y finalmente muestre la secuencia invertida.

In [ ]:
a = input("Introduzca un texto: ")
l = []

for i in a:
  l.append(i)
  
l.reverse()
print(l)

Introduzca un texto: Daniel Enrique
['e', 'u', 'q', 'i', 'r', 'n', 'E', ' ', 'l', 'e', 'i', 'n', 'a', 'D']


Ejercicio 2

Crea un programa que lea dos strings de la misma longitud, los guarde intercalados en una lista. Por último, mostrar el contenido de la lista.
Por ejemplo, si introducimos hola caracola y adios marieta, debería mostrarse haodleao scamraarcioeltaa.

In [ ]:
string1 = input("Introduzca la primera palabra/frase: ")
string2 = input("Introduzca la segunda palabra/frase: ")
s = []


if len(string1) == len(string2): 
  for i in range(len(string2)): 
    s.append(string1[i])
    s.append(string2[i])
  print(s)
else:
  print("Los textos deben tener la misma londitud")


Introduzca la primera palabra/frase: Daniela
Introduzca la segunda palabra/frase: Isabela
['D', 'I', 'a', 's', 'n', 'a', 'i', 'b', 'e', 'e', 'l', 'l', 'a', 'a']


Ejercicio 3

Crea un programa que lea un string y guarde en una lista todas las consonantes.

In [ ]:
a = input("Introduzca un texto: ")
a_min = a.lower()
l = []

for i in a_min:
  if i == "a" or i == "e" or i == "e" or i == "i" or i == "o" or i == " ":
    continue
  l.append(i) 
print(l)

Introduzca un texto: La naranja se pico
['l', 'n', 'r', 'n', 'j', 's', 'p', 'c']


Ejercicio 4

Crea un programa que lea una palabra, la guarde en una lista y compruebe si se trata de un palíndromo.

In [ ]:
a = input("Introduzca una palabra/frase: ")
a_min = a.lower()
l = []
m = []
count=0

for i in a_min:
  if i != " ":
    l.append(i)

for j in a_min:
  if j != " ":
    m.append(j)
m.reverse()

for k in range(len(l)):
  if m[k] == l[k]:
    count += 1 

if count == len(l):
  print(f"La palabra/frase {a} es un palindromo")
else:
  print(f"La palabra/frase {a} NO es un palindromo")
 

Introduzca una palabra/frase: Lavan esa base naval
La palabra/frase Lavan esa base naval es un palindromo
['l', 'a', 'v', 'a', 'n', 'e', 's', 'a', 'b', 'a', 's', 'e', 'n', 'a', 'v', 'a', 'l']
['l', 'a', 'v', 'a', 'n', 'e', 's', 'a', 'b', 'a', 's', 'e', 'n', 'a', 'v', 'a', 'l']


Ejercicio 5

Crea un programa que lea una matriz 3 x 3 y devuelva el máximo de cada fila.

In [ ]:
A = []
for i in range(3):
  A.append([])
  for j in range(3):
    A[i].append(float(input(f"Introduce el elemento de la fila {i+1} columna {j+1}: ")))

for i in range(3):
  A[i].sort(reverse = True) 
  print(f"El maximo de la fila {i+1} es {A[i][0]}")

Introduce el elemento de la fila 1 columna 1: 8
Introduce el elemento de la fila 1 columna 2: 6
Introduce el elemento de la fila 1 columna 3: 9
Introduce el elemento de la fila 2 columna 1: 10
Introduce el elemento de la fila 2 columna 2: 5
Introduce el elemento de la fila 2 columna 3: 6
Introduce el elemento de la fila 3 columna 1: 8
Introduce el elemento de la fila 3 columna 2: 9
Introduce el elemento de la fila 3 columna 3: 3
El maximo de la fila 0 es 9.0
El maximo de la fila 1 es 10.0
El maximo de la fila 2 es 9.0


Ejercicio 6

Crea un programa que lea un entero, n, de teclado y construya una matriz de tamaño n × n. Cada posición debe contener su orden en la matriz (desde 0 hasta n2 − 1. Por ejemplo, si n es 3, deberá crearse la matriz

[0, 1, 2]

[3, 4, 5]

[6, 7, 8]

In [ ]:
A = []
n = int(input("Introduzca el orden de la matriz: "))
count = 0

for i in range(n):
  A.append([])
  for j in range(n):
    A[i].append(count)
    count +=1

for i in range(n):
  print(A[i])


Introduzca el orden de la matriz: 10
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
[30, 31, 32, 33, 34, 35, 36, 37, 38, 39]
[40, 41, 42, 43, 44, 45, 46, 47, 48, 49]
[50, 51, 52, 53, 54, 55, 56, 57, 58, 59]
[60, 61, 62, 63, 64, 65, 66, 67, 68, 69]
[70, 71, 72, 73, 74, 75, 76, 77, 78, 79]
[80, 81, 82, 83, 84, 85, 86, 87, 88, 89]
[90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


Ejercicio 7

Crea una matriz de n × m y asigna los valores manualmente. El programa debe indicar si la suma de cada columna es el mismo valor.

In [ ]:
n = int(input("Introduzca el numero de filas de la matriz: "))
m = int(input("Introduzca el numero de columnas de la matriz: "))
A = []
B = []


for i in range(n):
  A.append([])
  for j in range(m):
    A[i].append(float(input(f"Introduce el elemento de la fila {i+1} columna {j+1}: ")))

for j in range(m):
  sum = 0
  for i in range(n):
    sum += A[i][j]
  B.append(sum)
print(B)

sum_equal = True
for j in range(m-1):
  if B[j] != B[j+1]:
      sum_equal = False

print("La suma de las columnas {}".format("Es igual" if sum_equal else "No es igual"))
  

Introduzca el numero de filas de la matriz: 2
Introduzca el numero de columnas de la matriz: 2
Introduce el elemento de la fila 1 columna 1: 2
Introduce el elemento de la fila 1 columna 2: 2
Introduce el elemento de la fila 2 columna 1: 2
Introduce el elemento de la fila 2 columna 2: 2
[4.0, 4.0]
La suma de las columnas Es igual


Ejercicio 8

Crear un programa determina si la matriz introducida manualmente (tanto sus dimensiones como los elementos) se trata de la matriz identidad. Recuerda que la matriz identidad debe ser una matriz cuadrada.

In [ ]:
n = int(input("Introduzca el numero de filas de la matriz: "))
m = int(input("Introduzca el numero de columnas de la matriz: "))
A = []
B = []


n_equal_m = True       # Bloque que comprueba que el numero de filas es igual al de columnas
if n != m:
  n_equal_m = False

for i in range(n):
  A.append([])
  for j in range(m):
    A[i].append(float(input(f"Introduce el elemento de la fila {i+1} columna {j+1}: ")))

ident = True            # Bloque que determina si los valores de la diagonal de la matriz son 1
for i in range(n):
  for j in range(m):
    if n < m:
      if A[i][i] != 1:
        Trans = False
    else:
      if A[j][j] != 1:
        ident = False

for j in range(m):     # Bloque que suma las columnas de la matriz
  sum = 0
  for i in range(n):
    sum += A[i][j]
  B.append(sum)

sum_equal = True       # Bloque que comprueba que la suma de las columnas es 1
for j in range(m):
  if B[j] != 1:
      sum_equal = False  


print("La matriz {}".format("es de Identidad" if ident and sum_equal and n_equal_m else "No es de Identidad"))

Introduzca el numero de filas de la matriz: 2
Introduzca el numero de columnas de la matriz: 2
Introduce el elemento de la fila 1 columna 1: 5
Introduce el elemento de la fila 1 columna 2: 6
Introduce el elemento de la fila 2 columna 1: 1
Introduce el elemento de la fila 2 columna 2: 9
La matriz No es de Identidad


Ejercicio 9

Realiza un programa que calcule la matriz transpuesta.

In [ ]:
import numpy as np

n = int(input("Introduzca el numero de filas de la matriz: "))
m = int(input("Introduzca el numero de columnas de la matriz: "))
A = []

for i in range(n):
  A.append([])
  for j in range(m):
    A[i].append(float(input(f"Introduce el elemento de la fila {i+1} columna {j+1}: ")))
print(A)

B = np.array(A)
print(B.T)


Introduzca el numero de filas de la matriz: 5
Introduzca el numero de columnas de la matriz: 2
Introduce el elemento de la fila 1 columna 1: 2
Introduce el elemento de la fila 1 columna 2: 6
Introduce el elemento de la fila 2 columna 1: 9
Introduce el elemento de la fila 2 columna 2: 1
Introduce el elemento de la fila 3 columna 1: 5
Introduce el elemento de la fila 3 columna 2: 2
Introduce el elemento de la fila 4 columna 1: 6
Introduce el elemento de la fila 4 columna 2: 1
Introduce el elemento de la fila 5 columna 1: 5
Introduce el elemento de la fila 5 columna 2: 9
[[2.0, 6.0], [9.0, 1.0], [5.0, 2.0], [6.0, 1.0], [5.0, 9.0]]
[[2. 9. 5. 6. 5.]
 [6. 1. 2. 1. 9.]]


Ejercicio 10

Crea un programa que pida al usuario la dimensión y cree la matriz identidad de orden correspondiente con numpy.

In [ ]:
import numpy as np

n = int(input("Introduzca la dimension de la matriz: "))

A = np.identity(n)
print(A)

Introduzca la dimension de la matriz: 50
[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
