# La salida del templo

Entraron en la nueva sala y las puertas de piedra se cerraron tras ellos. Se giraron sobre sí mismos y observaron la gran y solitaria habitación en la que se encontraban.

Volvían a estar entre 4 paredes de piedra tan altas como las anteriores. Esta vez solo 2 de ellas tenían una ventana pequeña y cuadrada en lo más alto. La pared que quedaba tras ellos tenía solamente la gran puerta por la que habían entrado. Y en la pared opuesta podía verse otra puerta muy diferente a todas las anteriores.

Esta nueva puerta era un poco más pequeña y brillaba, pues era de oro macizo. Pero lo que más emocionó a Pyratilla y su tripulación fue que en letras grandes y brillantes ponía: SALIDA AL EXTERIOR. A punto estaban de correr hacia la puerta cuando en el centro de la habitación apareció un altar. Con cautela, los tres piratas se acercaron al altar.

El primero en llegar fue Pyratilla y en voz alta empezó a leer:

<dl>
<dd>"Esta es la prueba final:</dd>
<dd>al superarla al exterior podrás salir</dd>
<dd>un cuadrado perfecto vas a crear</dd>
<dd>y para ello las instrucciones debes seguir."</dd>
</dl>

Al pronunciar la última palabra, el texto del altar cambió mágicamente y ahora se leía:

<dl>
<dd>"INSTRUCCIONES:</dd>
<dd>Utiliza el módulo numpy</dd>
<dd>Dados los arrays a, b, c, d y e, concátenalos de modo que</dd>
<dd>* sea un array bidimensional</dd>
<dd>* su shape sea (5, 5)</dd>
<dd>* cada fila sume 65</dd>
<dd>* cada columna sume 65</dd>
<dd>* cada diagonal sume 65</dd>
<dd>PISTA: El número de la mala suerte ocupa el lugar central</dd>
<dd>Cuando lo hayas construido,</dd>
<dd>* comprueba la dimensión con el método correspondiente</dd>
<dd>* comprueba la shape con el método correspondiente</dd>
<dd>* comprueba que cada fila suma 65 con el método correspondiente</dd>
<dd>* comprueba que cada columna suma 65 con el método correspondiente</dd>
<dd>* comprueba que cada diagonal suma 65 con un método creado por ti</dd>
<dd>* con el método .ndenumerate() indica los índices de los elementos que son mayores a la media de los elementos del array bidimensional construido y los que no lo son</dd>
<dd>* muestra los elementos que sí han superado el filtro de ser mayores a la media de los elementos del array bidimensional construido"</dd>

</dl>


In [1]:
import numpy as np

In [ ]:
a = np.array([[17, 5, 13, 21, 9]])
b = np.array([[23, 6, 19, 2, 15]])
c = np.array([[4, 12, 25, 8, 16]])
d = np.array([[11, 24, 7, 20, 3]])
e = np.array([[10, 18, 1, 14, 22]])

f = np.concatenate((d,c,a,e,b), axis = 0)

print(f)

In [ ]:
print(f"El array f tiene {f.ndim} dimensiones")

In [ ]:
print(f"La shape del array es de {f.shape}")

In [ ]:
for i in f:
  print(f"La suma de los elementos de la fila: {i} es {np.sum(i)}\n")

In [ ]:
for j in np.hsplit(f, 5):
  print(f"La suma de los elementos de la columna: \n{j} es {np.sum(j)}\n")

In [ ]:
def suma_diagonales(y):
  n = y.shape[0]
  suma_diag_principal = 0
  suma_diag_secundaria = 0
  
  for i in range(n):
    suma_diag_principal += y[i,i]
    suma_diag_secundaria += y[i, (n-1) - i]

  return (suma_diag_principal, suma_diag_secundaria)


diag_principal, diag_secundaria = suma_diagonales(f) 
print(f"La suma de la diagonal principal es {diag_principal}")
print(f"La suma de la diagonal secundaria es {diag_secundaria}\n\n")

In [ ]:
for idx, k in np.ndenumerate(f):
  cant_items = f.shape[0]*f.shape[1]
  media = np.sum(f)/cant_items
  if media < k:
    print(f"EL valor {k} que se encuentra en el indice {idx} es mayor a la media de los elementos del array bidimensional")
  else:
    print(f"EL valor {k} que se encuentra en el indice {idx} es menor a la media de los elementos del array bidimensional")


In [19]:
f_mayor_media = f[f>media]
print(f"\n\nLos elementos mayor a la media son {f_mayor_media}")

[[11 24  7 20  3]
 [ 4 12 25  8 16]
 [17  5 13 21  9]
 [10 18  1 14 22]
 [23  6 19  2 15]]
El array f tiene 2 dimensiones
La shape del array es de (5, 5)
La suma de los elementos de la fila: [11 24  7 20  3] es 65

La suma de los elementos de la fila: [ 4 12 25  8 16] es 65

La suma de los elementos de la fila: [17  5 13 21  9] es 65

La suma de los elementos de la fila: [10 18  1 14 22] es 65

La suma de los elementos de la fila: [23  6 19  2 15] es 65

La suma de los elementos de la columna: 
[[11]
 [ 4]
 [17]
 [10]
 [23]] es 65

La suma de los elementos de la columna: 
[[24]
 [12]
 [ 5]
 [18]
 [ 6]] es 65

La suma de los elementos de la columna: 
[[ 7]
 [25]
 [13]
 [ 1]
 [19]] es 65

La suma de los elementos de la columna: 
[[20]
 [ 8]
 [21]
 [14]
 [ 2]] es 65

La suma de los elementos de la columna: 
[[ 3]
 [16]
 [ 9]
 [22]
 [15]] es 65

La suma de la diagonal principal es 65
La suma de la diagonal secundaria es 65


EL valor 11 que se encuentra en el indice (0, 0) es menor a la me