Ejercicio 1

Crea un array unidimensional de 9 elementos y transfórmalo en un array 3D. Muestra la dimensión y la shape antes y después del reshape.

In [18]:
import numpy as np

a = np.array([8, 89, 80, 58, 98, 25, 48, 26, 78])
print(f"La dimension de a  es {a.ndim}")
print(f"La shape de a  es {a.shape}")




La dimension de a  es 1
La shape de a  es (9,)


In [21]:
b = a.reshape(1,3,3)
print(b)
print(f"La dimension de b  es {b.ndim}")
print(f"La shape de b  es {b.shape}")

[[[ 8 89 80]
  [58 98 25]
  [48 26 78]]]
La dimension de b  es 3
La shape de b  es (1, 3, 3)


Ejercicio 2

Dados los arrays 2D [[-6, -5], [-4, -3], [-2, -1]] y [[1, 2], [3, 4], [5, 6]], concaténalos de modo que obtengas el array [[1, 2, -6, -5], [3, 4, -4, -3] [5, 6, -2, -1]].

In [29]:
a1 = np.array([[-6, -5], [-4, -3], [-2, -1]])
a2 = np.array([[1, 2], [3, 4], [5, 6]])

c = np.concatenate((a2, a1), axis = 1)
print(c)


[[ 1  2 -6 -5]
 [ 3  4 -4 -3]
 [ 5  6 -2 -1]]


Ejercicio 3

Dado el array 2D [[1, 2, 3], [-1, 0, 1], [4, 5, 6], [-4, 0, 4], [3, 2, 1], [-3,0, 3]], divídelo en 3 arrays 2D.

In [35]:
d = [[1, 2, 3], [-1, 0, 1], [4, 5, 6], [-4, 0, 4], [3, 2, 1], [-3,0, 3]]

e = np.array_split(d,3)

for i in e:
  print(i)

[[ 1  2  3]
 [-1  0  1]]
[[ 4  5  6]
 [-4  0  4]]
[[ 3  2  1]
 [-3  0  3]]


Ejercicio 4

Dado el array 2D [["ala", "delfín", "arroz"], ["cena", "kayak", "picnic"],["hoja", "gato", "elle"]], busca las palabras que sean palíndromos.

PISTA: Necesitarás una función universal.

In [47]:
def is_palindrom(word):
    
    word = word.lower()
    L = []
    M = []
    count=0

    for i in word:
      L.append(i)
    for j in word:
      M.append(j)
    M.reverse()

    for k in range(len(L)):
      if M[k] == L[k]:
        count += 1 
      
    if count == len(L):
      return True
    else:
      return False

is_palindrom = np.frompyfunc(is_palindrom, 1, 1)

f = np.array([["ala", "delfín", "arroz"], ["cena", "kayak", "picnic"],["hoja", "gato", "elle"]])
print(is_palindrom(f))

[[True False False]
 [False True False]
 [False False True]]


Ejercicio 5

Dado el array 1D ["cena", "frío", "kayak", "remo", "sol"]], ¿qué índice deberá ocupar el elemento “python” para que se mantenga el orden alfabético?

In [51]:
g = np.array(["cena", "frío", "kayak", "remo", "sol", "python"])
h = np.searchsorted(g, "python")

print(f"El elemento python deberá ocupar el índice {h} para que se mantenga el orden alfabético")

El elemento python deberá ocupar el índice 3 para que se mantenga el orden alfabético


Ejercicio 6

Crea un minijuego que piense un número aleatorio entre 1 y 10 y, hasta que no lo aciertes, te pida un número del 1 al 10. Cuando aciertes, tendrá que devolver el número de intentos y la frase: “¡¡¡ENHORABUENA!!! Has acertado el número que había pensado: el {}”. En caso de que falles, el juego deberá mostrar la frase:
“¡Has fallado! ¡Prueba otra vez!”

In [60]:
from numpy import random 

x = int(input("Introduzca un numero del 1 al 10: "))
y = random.randint(10)

while x != y:
  print("¡Has fallado! ¡Prueba otra vez!")
  x = int(input("Introduzca un numero del 1 al 10: "))
  
print(f"¡¡¡ENHORABUENA!!! Has acertado el número que había pensado: el {y}")


Introduzca un numero del 1 al 10: 1
¡Has fallado! ¡Prueba otra vez!
Introduzca un numero del 1 al 10: 2
¡Has fallado! ¡Prueba otra vez!
Introduzca un numero del 1 al 10: 3
¡Has fallado! ¡Prueba otra vez!
Introduzca un numero del 1 al 10: 4
¡¡¡ENHORABUENA!!! Has acertado el número que había pensado: el 4


Ejercicio 7

Crea un minijuego que piense un array 1D aleatorio de 5 elementos. Los elementos serán números enteros entre 1 y 20. Para cada intento, primero tendrá que pedir 5 números enteros del 1 al 20. El juego nos tendrá que decir cuántos números del array hemos acertado y cuántos números del array están bien colocados. El juego no termina hasta que no se hayan acertado todos los números pensados en la posición correspondiente. Al acabar, se tendrá que mostrar la frase: “¡¡¡ENHORABUENA!!! Has acertado el array que había pensado: {}”

In [93]:
from numpy import random 

y = random.randint(20, size = 5)
print(y)
count_equal_position = 0
count_equal = 0

while count_equal_position != 5 and count_equal != 5:
  L = []
  while len(L) < 5:
    x = int(input("Introduzca un numero del 1 al 20: "))
    if x > 20 or x < 1:
      print("El numero introducido esta fuera del rango especificado")
    else:
      L.append(x)
  z = np.array(L)

  for i in range(len(y)):
    if y[i] == z[i]:
      count_equal_position += 1

  for j in range(len(y)):
    if y[j] in z:
      count_equal += 1

  print(f"Has acertado {count_equal} numeros y {count_equal_position} posiciones")

print(f"¡¡¡ENHORABUENA!!! Has acertado el array que había pensado: {y}")



[14 14  4 16 16]
Introduzca un numero del 1 al 20: 14
Introduzca un numero del 1 al 20: 14
Introduzca un numero del 1 al 20: 4
Introduzca un numero del 1 al 20: 16
Introduzca un numero del 1 al 20: 16
Has acertado 5 numeros y 5 posiciones
¡¡¡ENHORABUENA!!! Has acertado el array que había pensado: [14 14  4 16 16]


Ejercicio 8

A partir de la lista [-3, -2, -1, 0, 1, 2, 3], genera dos arrays aleatorios 2D de size = (3, 4) y súmalos.

In [92]:
list_number = [-3, -2, -1, 0, 1, 2, 3]

array1 = random.choice(list_number, size = (3, 4))
array2 = random.choice(list_number, size = (3, 4))

print(np.add(array1,array2))

[[ 1  4 -3  4]
 [ 4  1  0  0]
 [ 0  0  1  5]]


Ejercicio 9

Crea una función universal que dado un array de strings devuelva el número total de vocales de cada string.

In [105]:
def count_vocals(word):
    
  word = word.lower()
  count=0

  for i in word:
    if i in ["a", "á", "e", "é", "i", "í", "o", "ó", "u", "ú"]:
      count += 1
  return count

count_vocals = np.frompyfunc(count_vocals, 1, 1)

f = np.array([["ala", "delfín", "arroz"], ["cena", "kayak", "picnic"],["hoja", "gato", "elle"]])

print(count_vocals(f))


[[2 2 2]
 [2 2 2]
 [2 2 2]]


Ejercicio 10

Crea una función universal que dados un array 1D de valores string y conjunto de strings, compruebe para cada elemento del array 1D, si está presente o no en el conjunto.